### ISSUE TITLE
ZaakType admin page gives 500 error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#101]
**Describe the bug**
The ZaakType admin page at /admin/catalogi/zaaktype/ gives the following error:

```html

Request Method: | GET
-- | --
http://localhost:8000/admin/catalogi/zaaktype/
2.2.4
NoReverseMatch
Reverse for 'catalogi_zaakobjecttype_changelist' not found. 'catalogi_zaakobjecttype_changelist' is not a valid view function or pattern name.
/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 668
/usr/local/bin/uwsgi
3.7.4
['.',  '',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
ma, 7 Okt 2019 09:14:29 +0000
```

**Comment by annashamray** [comment]
It looks that this error appears because `ZaakTypeAdmin` includes `ZaakObjectType` admin which doesn't exist anymore.
`ZaakObjectTypeAdmin` was removed during refactor in https://github.com/open-zaak/open-zaak/commit/7aa7e7d22bb788b8141d6a76b7c4c6ec4225a556

@sergei-maertens 
Should I return it or should I just exclude `ZaakObjectType` from `ZaakTypeAdmin`: https://github.com/open-zaak/open-zaak/blob/996e4e6159fd7600df13cf547a7f3b63d5481649/src/openzaak/components/catalogi/admin/zaaktypen.py#L152
