### ISSUE TITLE
When adding a Status, Rol or Resultaat, a new Zaak does not need to be created

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#113]
https://github.com/open-zaak/performance-test/blob/a0a9cc61b5c1ae821a9e004ef362ca8d6fd7e476/performance_test/locustfile.py#L202

https://github.com/open-zaak/performance-test/blob/a0a9cc61b5c1ae821a9e004ef362ca8d6fd7e476/performance_test/locustfile.py#L227

https://github.com/open-zaak/performance-test/blob/a0a9cc61b5c1ae821a9e004ef362ca8d6fd7e476/performance_test/locustfile.py#L306

**Comment by annashamray** [comment]
since `Zaak` object can have only one related `Resultaat` and adding infinite amount of `Rol` or `Status` objects to `Zaak` is not a realistic scenario, the creation of `Zaak` in these cases seems to be the simplest way to test them. 

In https://github.com/open-zaak/performance-test/pull/4 I excluded the creation of `Zaak` from overall task statistics. It should help to analyze response time only for `Rol`, `Resultaat` or `Status` creation
