### ISSUE TITLE
Zaak Status, implicit ordering used incorrectly, status ordering isn't done explicitly

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1213]
**General information**
Open Zaak version: 1.5.x (SWF), 1.7.x

**Describe the issue**
Open Zaak makes use of implicit ordering in components/zaken/models/zaken.py (current_status_uuid, self.status_set.first()) which seems incorrect. The expected order is that the last status of a zaak is the current status, however this currently has to be retrieved via self.status_set.order_by('datum_status_gezet').last()

A better way to do this would be to introduce explicit ordering on the Meta of the Status class comparable to how this is done on the StatusType class.

I've checked and status_set.first() seems to only be used in the above location.

Unsure if bug or enhancement, feel free to relabel.

**Comment by sergei-maertens** [comment]
Okay, I look into this and found some things:

* The API endpoint for zaken does a prefetch which orders the statussen. So, `Zaak.status` in the API will always be the most recent status by date that it was set (which has a unique-together constraint, so it cannot be ambiguous).
* The above thing is the reason why `self.status_set.first()` worked without failing _when using the API_.
* The model layer was ambiguous - since there was no explicit ordering in the queryset, Django itself then sorts by `pk` (see `django.db.models.query` for that). This may yield different results than the API endpoint if there were some parallel requests/race conditions going on (i.e. the most recent status was not the most recent DB record created).
* This ordering has now also been made explicit bij setting `Status.Meta.ordering = ("-datum_status_gezet",)`

**Comment by alextreme** [comment]
Great, appreciated!
