### ISSUE TITLE
Zaak einddatum can be set while Zaak status isn't an 'eindstatus'

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1214]
General information
Open Zaak version: 1.5.x (SWF), 1.7.x

**Describe the issue**
Encountered by SWF as part of a migration making use of the ZGW APIs of Open Zaak.

It currently is possible to 'reopen' Zaken by adding a non-'eindstatus' Status to a Zaak with a current Status being the eindstatus. This means that the 'einddatum' of the Zaak is set, however the Zaak's latest Status (ordering issue: #1213 ) is something other than the last statustype (eg. isn't an eindstatus).

This leads to Zaken with an einddatum (Zaak is closed) but without having the current status being an eindstatus, which doesn't seem correct.

Options:
1. This is expected behaviour, ZGW APIs allow you to have your Zaak in an inconsistent state, client should know better.
2. This is not expected behaviour, Zaken API should not allow you to add a non eindstatus to a Zaak with an einddatum
3. This is not expected behaviour, Zaken API should allow you to add a non eindstatus to a Zaak but this should lead to the Zaak einddatum being cleared (effectively reopening the Zaak).

Unsure if bug or enhancement, feel free to relabel.

**Comment by sergei-maertens** [comment]
The standard is explicit about it: https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/index#zrc-008

> Bij het heropenen van een Zaak MOET de client een andere status toevoegen aan de zaak dan een eindstatus. (...)

> Tevens MOET de provider de volgende velden op null zetten zodra een eindstatus wordt gewijzigd in een andere status:

> * `Zaak.einddatum`
> * `Zaak.archiefactiedatum`
> * `Zaak.archiefnominatie`

So option 3 applies - looks like a bug on our end!

**Comment by sergei-maertens** [comment]
I'm suspecting a race condition as part of the migration, since re-opening a case _does_ reset the attributes specified in the standard - unless something is wrong with this test: https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/components/zaken/tests/test_zaak_closed.py#L135

Additionally, after having seen the data and the statuses being set in the same second, there may be an implicit ordering problem here. Though I find that a bit weird considering the `unique_together = ("zaak", "datum_status_gezet")` on Status model

**Comment by alextreme** [comment]
Okay, let's keep an eye on this in case it reoccurs elsewhere.
