### ISSUE TITLE
GET Zaak returns verlenging object even though there is no verlenging

### ISSUE THREAD

**Issue by JesseRoxit** [open-zaak/open-zaak#1228]
**General information**
Open Zaak version: tested on 1.5, suspect also in newer versions but haven't been able to test.

**Describe the bug**
On calling GET zaak, for a zaak which has no verlenging, we still get a verlenging object in the response. But the verlenging object has default values for the properties.

**To Reproduce**
1. Create a zaak without a verlenging
2. Call get zaak (by ID) API
3. Check response and see there is a verlenging object but with default values:

`"verlenging": { "reden": "", "duur": null }`

**Expected behavior**
I would expect that the verlenging object would be null when there is no verlenging.

**Comment by JesseRoxit** [comment]
Same goes for `Zaak.Opschorting` `EnkelvoudigInformatieObject.Ondertekening` and `EnkelvoudigInformatieObject.Integriteit` and possibly more.

**Comment by sergei-maertens** [comment]
Seems like the current response indeed does not match the API schema documentation at https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/zaken-api/1.1.2/src/openapi.yaml#tag/zaken/operation/zaak_read

Thanks for pointing this out, we'll add it to the community support project board.

**Comment by sergei-maertens** [comment]
> Same goes for `Zaak.Opschorting` `EnkelvoudigInformatieObject.Ondertekening` and `EnkelvoudigInformatieObject.Integriteit` and possibly more.

Opschorting is correct, because there is a boolean (default `False`) to check: `opschorting.indicatie`. `opschorting.reden` may be left empty according to the API spec. The intent behind "gegevensgroepen" from VNG was always that all of the fields are present.

`EnkelvoudigInformatieObject.Ondertekening` - the `soort` can be empty, implying it has not been signed. Checked this with the reference implementation, and the behaviour is consistent. The same applies for `EnkelvoudigInformatieObject.Integriteit` - if no algorithm is set, it has not been signed.

I definitely understand the confusion, but I think it should be taken up with the standard to define the desired behaviour. Either all keys are always present (and may be `null` / left out during writes), or if the gegevensgroep is considered "empty" then `null` should be returned.
