### ISSUE TITLE
Improve performance in Besluiten-list

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1400]
Version: [1.8.2-performance-fixes](https://github.com/open-zaak/open-zaak/releases/tag/1.8.2-performance-fixes)

Both Besluiten and EnkelvoudigInformatieobject, retrieve a Zaak for each Besluit/EIO. This should be optimized with a prefetch/select related:

You can see this behaviour here (for a list of 100 besluiten, it does 100x 1 query for each related zaak):

![image](https://github.com/open-zaak/open-zaak/assets/96970/aef00be0-116e-4838-b9d6-e880b85a6753)

No prefetch:

![image](https://github.com/open-zaak/open-zaak/assets/96970/d1f60663-c6dd-40ca-a2a2-73a0b44a8edf)

Caused by the `__init__` method:

![image](https://github.com/open-zaak/open-zaak/assets/96970/6e91c194-5290-4022-b3df-d6c9ed9575c0)

**Comment by annashamray** [comment]
After very long and painful debugging I localized the part that hits DB for ZaakIdentificatie. It's this line:
https://github.com/open-zaak/open-zaak/blob/ccb1b02fa6c19c07e0b5c13cdd6ca3da26703949/src/openzaak/components/besluiten/models.py#L200

It turned out that calling field descriptor with concrete inheritance in the __init__ was not a good idea 
I'll make DB fields for `Besluit.previous_zaak` as an optimization here
