### ISSUE TITLE
Create zaak returns 403 instead of 404 if zaaktype doesn't exist

### ISSUE THREAD

**Issue by damm89** [open-zaak/open-zaak#1481]
**General information**
Open Zaak version: 1.8.2

**Describe the bug**
If `zaaktype` doesn't exist when creating a `zaak` a 403 is returned instead of a 404. This is confusing behavior when debugging the cause of the 4xx response.

**To Reproduce**
1. Make sure `zaaktype` doesn't exist
2. Create `zaak` with non-existing `zaaktype`.

**Expected behavior**
A 404 detailing what is not found. I.e., <zaaktype-url> is not found or similar.

**Comment by joeribekker** [comment]
Refinement: Can be picked up under Utrecht. @annashamray please check in the VNG spec if this is documented as such or that we can change this.

**Comment by annashamray** [comment]
@damm89 I think 404 should be raised then a fetched resource is not found, here the resource `<zaken api>/api/v1/zaken` is present. So 400 should be a better fit here.

@joeribekker I've found in the VNG documentation (https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/) that in this situation 400 status is expected:
> Bij het aanmaken (zaak_create) of bijwerken (zaak_update, zaak_partial_update) van een zaak MOET de URL-referentie naar het zaaktype gevalideerd worden op het bestaan. Indien het ophalen van het zaaktype niet (uiteindelijk) resulteert in een HTTP 200 status code, MOET het ZRC antwoorden met een HTTP 400 foutbericht.

But on the other hand 403 is also kind of logical here, because the authorization in the Zaken API is coupled to zaaktypen. First we check Autorisaties API with the provided zaaktype and if the authorization is not found we stop the process and return 403. 
Validation of the zaaktype before permission check will result in more DB queries and perhaps more external requests (we need to check it).  Should I proceed with it?

**Comment by damm89** [comment]
I see your argument against a 404 but a 403 is highly confusing. If the 403
is deemed appropriate in the end, please consider changing the descriptive
text in the response.

**Comment by joeribekker** [comment]
I think 403 is the most appropriate. It's not a (400) bad request, since the request itself is valid. A 404 would be weird since the endpoint exist and it's only further down the process that something doesn't exist but only due to permissions.

Changing the text however might be good. Can we do that Anna or is it some generic flow?

**Comment by annashamray** [comment]
In the Autorisaties component we store zaaktypen as urls, because they can also be external. And we check if `zaaktype` for user input is present in Autorisaties just comparing url strings. This is our flow. In order to change the text we need to change the flow and to validate the url first. But in this case we can just through 400 status like the standard suggests.

**Comment by joeribekker** [comment]
Refinement: 400 it is.
