### ISSUE TITLE
`OPENZAAK_REWRITE_HOST` & `OPENZAAK_DOMAIN` breaks OIDC login

### ISSUE THREAD

**Issue by sjoerdie** [open-zaak/open-zaak#1585]
**General information**
Open Zaak version: 1.11.0

**Describe the bug**
When setting `OPENZAAK_REWRITE_HOST` and `OPENZAAK_DOMAIN` the OIDC redirect url is set to `OPENZAAK_DOMAIN` value, causing OIDC login to fail.

**To Reproduce**
1. Set `OPENZAAK_REWRITE_HOST=true`, `OPENZAAK_DOMAIN=api.gateway.example.com`
2. Configure your OIDC provider
3. Try to login with OIDC.

**Expected behavior**
From the change logs: https://github.com/open-zaak/open-zaak/blob/c52837c37912698b7f674d979c3c0617bc62e8e0/CHANGELOG.rst#L274

We expect the domain rewrite only to happen for API calls, this is what the docs imply. The redirect uri for OIDC should remain the domain openzaak is hosted on.

**Comment by alextreme** [comment]
@stevenbal please pick this up, @annashamray can then review

**Comment by sergei-maertens** [comment]
Note that this setting was added as a last resort, the proper way to configure things is to use the X-Forwarded-Host header.

This should probably be added as a disclaimer in the documentation: https://open-zaak.readthedocs.io/en/stable/installation/reference/fq-urls.html?highlight=OPENZAAK_REWRITE_HOST#forcing-host-rewrites because this feature is a dirty hack in itself to address some extremely specific use cases, like NLX where no (semi-)public URL exists.

**Comment by annashamray** [comment]
Restricting rewriting host will probably mess up authorizations, please take a look at my comment in the PR: https://github.com/open-zaak/open-zaak/pull/1588#pullrequestreview-1980268321

Let 's discuss it during refinement

**Comment by joeribekker** [comment]
Refinement: Steven looks into how much work it is to adjust authorizations to not save absolute URLs so they dont need to be rewritten in the first place. If this turns out to be alot of work, we go for the bandaid solution: use openzaak domain to rewrite stuff in authorizations admin.

**Comment by stevenbal** [comment]
I don't think the original PR https://github.com/open-zaak/open-zaak/pull/1588#pullrequestreview-1980268321 creates issues with the authorization mechanism itself (from what I can see), the only issue is that notifications triggered by saving the Autorisaties form in the admin don't rewrite the hosts for the `Applicatie` resource (because the request that triggers them is a request to the admin and not the API). I think the solution for this is to make sure that the host overriding does happen for this admin triggered notification flow (https://github.com/open-zaak/open-zaak/blob/bdf1144378ae1e6b25daa971e3575d12582044a0/src/openzaak/components/autorisaties/utils.py#L96)

To be sure I tested locally with `OPENZAAK_DOMAIN` and `OPENZAAK_REWRITE_HOST` , saved the authorizations and then requested resources using this `Applicatie` and this seems to work.

I did notice that `loader.is_local_url` (https://github.com/open-zaak/open-zaak/blob/bdf1144378ae1e6b25daa971e3575d12582044a0/src/openzaak/components/autorisaties/admin_views.py#L57-L65) doesn't work locally due to port numbers not being stripped off, but the URLs being local or not doesn't actually seem to matter? I guess it doesn't matter what URL is saved on the authorization, because Open Zaak itself will always be able to retrieve it, whether it uses the internal domain or `OPENZAAK_DOMAIN`. I might be overlooking something here, I'm not entirely sure how the authorization/authentication mechanism works in full detail.

Even if we wanted to make authorizations to store relative URLs to zaaktypes/iotypes/besluittypes, I think this would cause issues because the underlying `Autorisatie` model is part of commonground-api-common (https://github.com/maykinmedia/commonground-api-common/blob/main/vng_api_common/authorizations/models.py#L79-L84), and this same model is also used by Open Notificaties (which will need the full URLs)

**Comment by stevenbal** [comment]
I created a separate issue in django-loose-fk for the `is_local_url` issue: https://github.com/maykinmedia/django-loose-fk/issues/32

**Comment by joeribekker** [comment]
Refinement: @annashamray Steven wants to hear your thoughts on this issue because he thinks authorizations is not an issue.

**Comment by annashamray** [comment]
@stevenbal I don't quite understand. `send_applicatie_changed_notification` doesn't deserialize local zaaktypes to urls. It takes Autorisaties data and send them as it is, right? 

Let's discuss the example. OZ is hosted on host "server.local", OPENZAAK_DOMAIN="oz.nl"
1. Admin user goes to Autorizaties admin page at "https://server.local/admin" and creates new autorisatie by selecting some local zaaktype from the list
2. Autorisatie is saved into DB, the `zaaktype` field has url "https://server.local/zaken/api/v1/<uuid>"
3. Notifications is send with this zaaktype

Is this what we expect to happen? 
If yes, I think rewriting urls only in notifications would lead to confusions, because we will have different data in notifications and in DB. I think we should modify zaaktype url before saving it to the DB (in the example it's the 2nd step), and send notification as usual. Or just don't save urls for local zaaktypes to DB at all.

**Comment by annashamray** [comment]
**UPD** I made a comment above before seeing your implementation, where you rewrite urls before saving Autorisatie. I think it's a way to go if we don't want to refactor all autorisaties.

**Comment by joeribekker** [comment]
Discussed in weekly and it turned out @sjoerdie made it work using Nginx X_FORWARD_HOST and SUBPATH env var and not using the OPENZAAK_DOMAIN env.

Decided to try the X_FORWARDED_HOST in Nginx combined with USE_X_FORWARDED_HOST in Django, in Rotterdam to see if this works well, then we can consider deprecating OPENZAAK_DOMAIN.

For now, we can merge this.

**Comment by sergei-maertens** [comment]
> then we can consider deprecating OPENZAAK_DOMAIN

Keep in mind that this setup is required if you *only* expose Open Zaak via NLX, there is then no public/stable domain where OZ is hosted because each consumer has their own outway address.

**Comment by joeribekker** [comment]
I'll make a new issue for this comment from sergei.
