### ISSUE TITLE
DRC OpenAPI spec contains 'format: byte' instead of 'format: bytes' which results in non-functional generated Java stub code

### ISSUE THREAD

**Issue by edgarvonk** [open-zaak/open-zaak#1704]
### Product versie / Product version

1.13.0

### Omschrijf het probleem / Describe the bug

The new DRC OpenAPI spec in OpenZaak contains `format: byte` for some (but not all..) `inhoud` fields. I think this should be: `format: bytes`. The OpenAPI spec as it is now results in non-functional generated Java stub code: the `inhoud` fields are then of type `byte[]` but it should be a `String` (like it was in the old version of this spec). In this String inhoud field we then set the contents of the file as Base64 encoded string. With `format: bytes` the `inhoud` fields are generated correctly to `String`.

### Stappen om te reproduceren / Steps to reproduce

1. Generate Java stub code from the DRC OpenAPI spec using https://github.com/OpenAPITools/openapi-generator
2. The generated Java code contains code `private byte[] inhoud;` for inhoud fields
3. This code cannot be used to create enkelvoudigeinformatieobjecten in OpenZaak using the DRC API. OpenZaak responds with the error: "rest_framework.exceptions.ValidationError: {'inhoud': [ErrorDetail(string="argument should be a bytes-like object or ASCII string, not 'list'", code='invalid')]}"

### Verwacht gedrag / Expected behavior

Enkelvoudigeinformatieobjecten can be created in OpenZaak using Java stub code generated from the DRC OpenAPI spec.

**Comment by annashamray** [comment]
@edgarvonk 
I can't see `bytes` as an allowed format for OAS v3 - https://swagger.io/specification/v3/?sbsearch=Data%20Type%20Formats%20#data-types 

Could you provide a link to the OAS standard where format `bytes` is more preferable than `byte` ?

**Comment by edgarvonk** [comment]
Hi @annashamray , I am not knowledgeable about the OAS V3 standard I'm afraid. The only thing I know is that with `byte` our generated Java stub code is unusable (see above). So I reverted the spec manually back to `bytes` which was used in the old version of the spec..

**Comment by annashamray** [comment]
@joeribekker What do you think?

**Comment by edgarvonk** [comment]
@annashamray I understand that you are also testing the OpenAPI specs by generating Java stub code right? If so, you do not run into my reported issue in this case? Can you maybe point me to how you generate this Java code?

**Comment by joeribekker** [comment]
@annashamray this is where it gets more fuzzy:

1. We should adhere to the Open API Specification
2. We should generate stub-code to see if the code generators can handle it.

Typically, the code generators are more picky and usually only support slightly older versions of the OAS (ie. v3.0 instead of 3.1)

To make things practical, both should simply be taken into account. Hence the #1709 ticket.

**Comment by joeribekker** [comment]
As far as we [can tell](https://swagger.io/specification/v3/?sbsearch=Data%20Type%20Formats%20#data-types), the OAS specification indicates the only valid format is "byte", not "bytes".

![Image](https://github.com/user-attachments/assets/6315cf74-ef1f-42e1-b012-c165f0151ac9)

The only thing I can think of, is that the generator does it wrong.

Since we're not changing this, I'm closing this ticket.
