### ISSUE TITLE
Documenten API: bij filteren op trefwoorden OR-relatie ipv AND-relatie hanteren

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1774]
### Thema / Theme

Documenten API

### Omschrijving / Description

Taiga DH 590 nr 2

> We willen kunnen filteren op "OF" bij trefwoorden/tags, het is nu alleen maar "EN". Als bijvoorbeeld iemand alle documenten wil zien met tag "ID bewijs" of "afschrift nota". Dan krijg je nu dus alleen de documenten te zien die beide tags heeft, maar dat komt dus niet veel voor.

So, this would mean modifying the ?trefwoorden=foo,bar document-list query option. Available choices in my eyes:

1. Modify it in-place, with the risk that this may interfere/break existing integrations/expectations
2. Put this change behind a featureflag
3. Add a ?trefwoorden_or=foo,bar query option so we support both

**Comment by joeribekker** [comment]
Refinement: The `trefwoorden` query parameter already uses "contains" under the hood, which mimicks the AND operator for all values (`?trefwoorden=a,b` ~ trefwoorden has a AND trefwoorden has b). We can add the `overlap` operator since it has a counterpart in Django, to make it clear to devs, which mimicks the OR operator (`?trefwoorden__overlap=a,b` ~ trefwoorden has a OR trefwoorden has b).

Should be marked as experimental.

Estimate: 2 days

@PeterVanBragt: ready for approval.

**Comment by alextreme** [comment]
Extra context via Thomas:

EN Filter

vanuit een gebruikersperspectief zou ik verwachten dat het mogelijk is om op Informatieobjecttype, Vertrouwelijkheidaanduiding en Trefwoorden gefilterd kan worden op “OF” en niet “EN”.

Bijvoorbeeld bij de afdeling Schuldhulpverlening wil op een verzameling van informatieobjecttypes kunnen filteren en alle behorende documenten zien. Zodat ze bijvoorbeeld alle documenten kunnen inzien die te maken hebben met bijvoorbeeld inkomsten en uitgaven. Hieronder staat een overzicht voorbeeld van Schuldhulpverlening per onderwerp welke informatieobjecttypes ze daarbij willen zien in de documententab. Met alleen een EN filter is dit niet mogelijk.

![image](https://github.com/user-attachments/assets/dbf931cc-ab3c-41e7-8fdc-13806f7a6145)

**Comment by PeterVanBragt** [comment]
Approved

**Comment by alextreme** [comment]
Released in Open Zaak v1.16.0
