### ISSUE TITLE
As stakeholder of OpenZaak I'd like a green API testplatform badge

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#328]
... so that we can show that OpenZaak is ZGW 1.0-compliant.

**Description**
With the ZGW 1.0 test-script as a mandatory part of the OpenZaak Travis pipeline we can rest assured that OpenZaak is ZGW 1.0 compliant.

However to show that this is the case I would like to have a scheduled daily test performed using @stevenbal 's api-test.nl and show the resulting badge on the openzaak.nl website and the openzaak github (just like on https://github.com/VNG-Realisatie/gemma-zaken/ )

I would suggest to do this using the API on test.openzaak.nl. 

![Screenshot_2019-12-12_16-07-27](https://user-images.githubusercontent.com/226839/70724062-354f1b80-1cfa-11ea-95d2-b7a93848ae9b.png)

**Comment by joeribekker** [comment]
As you indicated yourself, technically we already pass the test. We just don't show it since we don't do it via the api-test.nl platform.

This would require a new instance to be setup dedicated just for the api-test.nl platform.

Although I agree this is the best way, it takes work, structural resources and the take away is minor. Hence, I would suggest low prio.

**Comment by joeribekker** [comment]
Duurzaam testen (elke dag bijv.) is meer iets voor beheer en onderhoud en niet voor dit development project. We gaan de eenmalige check doen op 1.0.0 (of elke versie eigenlijk) via #362

**Comment by Hugo-ter-Doest** [comment]
Continu testen met het API Testplatform hoort niet in dit project thuis, maar bij Beheer en Onderhoud na oplevering van versie 1.0
