### ISSUE TITLE
As sysadmin, I want to see my JWT-token in the admin UI

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#400]
... so I can use it without generating it with some tool.

**Description**
It seems an undocumented `generate-jwt` commando exists in the gemma-zds-client package but let's just show the token in the admin UI.

Optionally, document this generate-jwt command.

**Comment by sergei-maertens** [comment]
@stevenbal can you modify the middleware as well so that JWTs expire after X hours after the issued time? The [`iat` claim](https://tools.ietf.org/html/rfc7519#page-10) is in the JWT and should be used as starting point. A setting to configure the number of hours of validity seems a good approach, with a default of 1 hour.
