### ISSUE TITLE
Forgetting to base64-encode file uploads errors instead of returning validation errors

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#608]
**Describe the bug**

Uploading an ENKELVOUDIGINFORMATIEOBJECT with binary data instead of base64-encoding this binary data throws an Internal Server Error.

**To Reproduce**
1. POST to /documenten/api/v1/enkelvoudiginformatieobject with an `inhoud` that is just the binary data instead of base64 encoding it (e.g. `pdf_file.read().encode("utf-8")`)

**Expected behavior**

The API should fail validation and return an error indicating that the client probably forgot to base64-encode the file data.

**Comment by SilviaAmAm** [comment]
I am trying to reproduce the issue by using inhouds that are:

1. A binary strings with characters A-Z,a-z,0-9 + padded with =, with a length multiple of 4 (causes no error).
2. A binary strings with characters A-Z,a-z,0-9 +, with a length NOT multiple of 4 (causes a 400 error, with helpful message).
3. A binary strings with characters OTHER THAN A-Z,a-z,0-9 + padded with =, with a length multiple of 4 (causes a 400 error, with helpful message).
4. A binary string from reading a pdf file, this causes an error when the inhoud is encoded to UTF-8, because there are bytes that are invalid UTF-8 characters (Causes a 400 error with error saying that the JSON couldn't be parsed).

I haven't managed to reproduce the 500 error yet though?
