### ISSUE TITLE
Running OpenZaak on Windows requires a Dos2Unix on docker_start.sh

### ISSUE THREAD

**Issue by rjzondervan** [open-zaak/open-zaak#633]
**Describe the bug**
When running open-zaak from docker-compose on Windows, the web-container crashes when starting start.sh (the docker entrypoint). This seems to be explained by the encoding of the docker_start.sh file in /bin. When I use the linux command dos2unix from a linux kernel in WSL, the container is usable after that.

**To Reproduce**
1. Clone the repository on a Windows machine
2. Run docker-compose up

**Expected behavior**
A running OpenZaak container after the build

**Actual behavior**
An error 'standard_init_linux.go:211: exec user process caused "no such file or directory"'

**Comment by sergei-maertens** [comment]
Oddly enough, on the master branch for my on a linux system, running `dos2unix` on the script makes no difference (at least nothing that git sees as a change).

Joeri, probably one for you to verify since you use Windows :)

**Comment by rjzondervan** [comment]
We spoke to Joeri about this last Tuesday, and we found that this is probably to do with git automatically encoding as dos (windows) file when pulling on Windows.
Ruben told us in that same conversation that there is probably a fix that would solve this, but that he would have to look it up.

**Comment by joeribekker** [comment]
Although I can reason about why this issue occurs, I could not reproduce it. I used `git` inside a `WSL` terminal and run Docker inside WSL as well.

The issue is most likely similar to this SO-post: https://stackoverflow.com/questions/53900839/git-repo-gives-contradictory-info-from-wsl-than-from-standard-windows

Maybe you ran Git on Windows (not WSL)?

I don't think this should be "fixed" since it's not a bug in Open Zaak but rather a side-effect of using Git on Windows. For developers that want to built their own image for testing.

I noticed the `docker-compose up` is not described in the documentation at all. I will add this and a note about Git on Windows.
