### ISSUE TITLE
As developer, I want to know how to register kanalen

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#743]
... so I can fully use Open Notificaties.

**Description**
There's several ways to make this clear. Either we indicate that it must be done via the API, or use the command `register_kanaal`, or add them by default?

**Comment by sergei-maertens** [comment]
Adding them by default is not ideal, since we don't know the source documentation URL. E.g. the channel `zaken` is registered by Open Zaak and the documentation is provided by the Open Zaak installation. So you need the Open Zaak installation URL to build the full documentation URL.

The `register_kanaal` (or maybe `register_kanalen`) management command in Open Zaak should just register all the relevant channels in my opinion, see #668

**Comment by sergei-maertens** [comment]
This is now documented as of 1.3.4
