### ISSUE TITLE
As Product Owner, I want to understand which measures and/or design decisions I have to take ...

### ISSUE THREAD

**Issue by sgort** [open-zaak/open-zaak#866]
... so I can make the product Virtueel Inkomensloket that I am developing for VNG Realisatie and Utrecht suitable for nationally scalable application that **includes** linking Open Zaak via NLX.

**Description**
The development team is currently working on getting the first scheme (the individual Income Allowance) to work technically in the Virtueel Inkomensloket. On the one hand, a front-end is being built, which is accessible to all residents and which enables residents to retrieve their own data from national data sources. On the other hand, a rule checker is being built through which the data of the resident is tested to determine whether the resident complies with the regulation. The Virtueel Inkomensloket is being developed radically open source (see [gitlab](https://gitlab.com/commonground/virtueel-inkomstenloket/poc_utrecht_iit) for all branches state to date). Everything we build is opened up to everything and everyone. This means that everyone is free to use it and to build with it.

There has been coordination with Lazo Bozarov. Partly on his behalf, I am hereby seeking contact with Maykinmedia via this issue.

**Comment by sergei-maertens** [comment]
@sgort 

Do I understand correctly that this would require Open Zaak API's to be available on the NLX network, so that the Virtueel Inkomensloket can fetch data from Open Zaak for certain residents?

**Comment by joeribekker** [comment]
I contacted you via CG slack :)

**Comment by sgort** [comment]
@sergei-maertens 

I think that's just about it, suspect posts are needed in addition to fetch...

**Comment by sergei-maertens** [comment]
Alright - what's the biggest thing to keep in mind at this moment is the requirement to rewrite URLs in API calls, which needs to be done by the **client**.

A typical set-up would be:

```
+--------------------+         +----------------------+
|                    |         |                      |
|  client -> outway  +--->->---+  inway -> Open Zaak  |
|                    |         |                      |
+--------------------+         +----------------------+
```

I.e. - the client makes the API call through the own inway:

```http
GET http://localhost:8080/<org>/zaken?zaaktype=<url> HTTP/1.1
Host: localhost:8080
Authorization: Bearer <token>
```

This arrives in the outway, the outway connects to the inway that provides the Open Zaak API's, and the inway translates the call to the internal Open Zaak service:

```http
GET http://open-zaak.local:8000/zaken/api/v1/zaken?zaaktype=<url> HTTP/1.1
Host: open-zaak.local:8000
Authorization: Bearer <token>
```

What you observe here, is that the local URL `http://localhost:8080` became `http://open-zaak.local:8000` for Open Zaak. Open Zaak only understands it's own local URLs, so the **client needs to rewrite all outway URLs to Open Zaak urls**.

If for example the zaaktype can be fetched with `http://localhost:8080/<org>/catalogi/zaaktypen/123`, then this literal URL cannot be in the querystring `?zaaktype=`, because Open Zaak cannot know what your outway address is. This is not an Open Zaak problem, this is for every service making use of URL references with NLX. The client **must** rewrite this URL to `http://open-zaak.local:8000/catalogi/api/v1/zaaktypen/123` first.

Consequently, in the responses the mirrored situation happens. For Open Zaak, the client is the inway, which calls the host `open-zaak.local:8000`, so all generated URLs in the response bodies and headers will be relative to this. The client must rewrite response bodies and headers from `http://open-zaak.local:8000/<prefix>` to the matching outway URL `http://localhost:8080/<org>/<service>`.

Other than that, Open Zaak should work without issues with NLX. The admin interface of Open Zaak also provides some configuration (`.toml`) examples on how to configure each Open Zaak API on the NLX network. You can definitely use this as inspiration for the NLX management UI as well.

**Comment by sjefvanleeuwen** [comment]
Hi Joeri already has this list. But to be complete in this thread is that for the ZTC on Virtueel Inkomensloket, some of the categories might be applicable accoording to GEMMA ZTC 2.0.

•	GEMMA Referentiezaaktype ‘Inkomens- of maatschappelijke ondersteuning verstrekken’ 20406

Voor (BPMN) processen:

	Periodieke inkomensondersteuning verstrekken
	Boete opleggen
	Afhandelingswijze vordering bepalen
	Regie arbeidsontwikkeling werkzoekende uitvoeren 
	Instrument arbeidsontwikkeling inzetten

•	GEMMA Referentiezaaktype ‘Administreren’ 30101

Voor (BPMN)  processen

	Melding mutatie periodieke inkomensondersteuning verwerken

•	GEMMA Referentiezaaktype ‘Toezicht houden’ 20801

Voor (BPMN) processen

	Maatregel opleggen
	Onderhoudsverplichting verhalen
	Bijzonder onderzoek uitvoeren (moet nog uitgewerkt worden)

•	GEMMA Referentiezaaktype ‘Adviseren’ 30102

Voor (BPMN) proceesen

•	Aanvraag advies dienstverlening inkomens- en maatschappelijke ondersteuning behandelen


Furthermore, there could be a sub categorie (deelzaak), for processes such as "Aanvraag levensonderhoud behandelen" for the "Periodieke Inkomensondersteuning Verstrekken"

My 2 cents.

**Comment by sjefvanleeuwen** [comment]
Another Idea I'd like to bounce of to the team of openzaak, is that Virtueel inkomenloket has local policies next to central government policies.

The local policies, such as "U-Pas verstrekken" could be normalized in openzaak, as Rotterdam has the Rotterdamse pas, but in essence they serve somewhat the same purpose (different norms). When a citizen moves from one Gemeente to another, it might be more optimal for the Business Processes to have the same ZTC deelzaak codes for scale up/tracability on the components that a ciziten needs for his/her self reliance.

I suppose Virtueel Inkomenloket could then help with transitioning the locality of a customer in its income trans-municipality.

**Comment by Hugo-ter-Doest** [comment]
To begin with zaken are handled within an organisation, Zaken are not meant to be handled across organisaties boundaries. Secondly, deelzaken must be customer-to-customer zaken just like ordinary zaken. Please read the section about deelzaken in https://www.gemmaonline.nl/index.php/Hoofd-_en_deelzaken_en_gerelateerde_zaken to see if you really need deelzaken. In most cases you need gerelateerde zaken. Deelzaken are not meant for a decomposition of zaken as needed from an operational perspective.  So, subprocesses are not the same as deelzaken.

If I read the discussion above, there are very technical issues and business topics discussed. I think a design of some sort will help to understand what is being pursued.

Components I read about so far are:
- Loket
- Electronic forms
- Rules engine
- OpenZaak
- Objectregistraties (for data that you cannot register in OpenZaak)
- Some portal for employees (with workflow support?)
- NLX

If these are set up in a generic way and can be configured (forms, zaaktypen, objecttypen, business rules, etc.) you can imagine that a complete range of products in the werk en inkomen domein can be handled on such a platform.

**Comment by sjefvanleeuwen** [comment]
Thank you Hugo for the clarification on bouncing this idea.

**Comment by sgort** [comment]
First thoughts functional decomposition for discussion purposes
![image](https://user-images.githubusercontent.com/25812095/108040485-a6483c80-703d-11eb-8524-990c6ce1e4c2.png)

**Comment by sgort** [comment]
Er blijkt al een proeftuin voor Utrecht te zijn: https://openzaak.utrechtproeftuin.nl/ en https://directory.demo.nlx.io/?q=utrecht

**Comment by joeribekker** [comment]
The ontology from the GBI can be in the [Objects API ](https://objects-and-objecttypes-api.readthedocs.io/) (also since GBI is stakeholder in that project).

**Comment by sgort** [comment]
Improved functional decomposition diagram
![image](https://user-images.githubusercontent.com/25812095/108081347-26d46080-7071-11eb-9083-624405fd3c68.png)

**Comment by sgort** [comment]
Dank voor support en hulp alhier. We pakken de zaak terug op in de 'eigen' [gitlab issue](https://gitlab.com/commonground/virtueel-inkomstenloket/poc_utrecht_iit/-/issues/43) hiertoe. Deze kan derhalve gesloten worden.
