### ISSUE TITLE
Onduidelijk of rechten worden onthouden bij applicatie aanmaken

### ISSUE THREAD

**Issue by jgabrieldelft** [open-zaak/open-zaak#978]
OZ 1.4.0
Bij het inrichten van een nieuwe (productie) omgeving het volgende tegengekomen:
-applicatie aangemaakt
-rechten toegewezen voor notificaties, documenten en zaken
-rechten opgeslagen
-rechten opnieuw bewerken: alleen rechten voor notificaties zijn onthouden en worden getoond
-ZTC ingelezen via importer
-rechten van applicatie opnieuw bewerken: de rechten voor documenten en zaken toont hij nu wel, dus waren kennelijk wel opgeslagen

Helaas geen printscreen, maar moet voor zichzelf spreken.
Nogal opmerkelijk, maar gelukkig functioneert het wel.

**Comment by sergei-maertens** [comment]
Need to check if this is still a thing - what happens here is that permissions cannot be displayed because they are a blueprint for current + future data (and there is no current data yet before importing, therefore it cannot be displayed).

I do remember working on this at some point, but we'll need to verify this.

**Comment by annashamray** [comment]
@sergei-maertens I found this resolved issue - https://github.com/open-zaak/open-zaak/issues/1080
But it looks like it was fixed only for Besluiten component. I'll add fixes for Zaken and Documenten

**Comment by sergei-maertens** [comment]
Looking at the patch, this seems to be a generic fix (but only a test for besluiten and not the others) - I would just quickly check on latest if the problem happens for zaken before diving into it too much.
